# Site settings
title: Dan's Dev Diary
description: >
  The Diary of a Music Producer turn Web Developer living in Tokyo, Japan. Working with startups to build apps that disrupt and innovate.

baseurl: "http://dansdevdiary.me" # the subpath of your site, e.g. /blog/
url: "http://dansdevdiary.me" # the base hostname & protocol for your site

author:
  fullname: Daniel Eddy
  github: z-daniel
  twitter: decreativedan
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
